export const machines = [
  {
    id: "lab-01",
    name: "Lab Station 01",
    gpu: "RTX 4090 24GB",
    cpu: "Ryzen 9 7950X",
    ram: "64GB",
    storage: "1.8TB",
    state: "available",
    cpuUsage: 8,
    gpuUsage: 0,
    owner: null,
    project: null,
  },
  {
    id: "lab-02",
    name: "Lab Station 02",
    gpu: "RTX 4090 24GB",
    cpu: "Ryzen 9 7950X",
    ram: "64GB",
    storage: "1.4TB",
    state: "busy",
    cpuUsage: 72,
    gpuUsage: 94,
    owner: "ts250021@ts.hs.kr",
    project: "YOLOv8 도로 객체 탐지",
  },
  {
    id: "lab-03",
    name: "Lab Station 03",
    gpu: "RTX 3090 24GB",
    cpu: "Core i9-13900K",
    ram: "32GB",
    storage: "820GB",
    state: "busy",
    cpuUsage: 46,
    gpuUsage: 81,
    owner: "ts250008@ts.hs.kr",
    project: "LLM Fine-tuning",
  },
  {
    id: "lab-04",
    name: "Lab Station 04",
    gpu: "RTX 3090 24GB",
    cpu: "Core i9-12900K",
    ram: "32GB",
    storage: "1.1TB",
    state: "available",
    cpuUsage: 3,
    gpuUsage: 0,
    owner: null,
    project: null,
  },
  {
    id: "lab-05",
    name: "Lab Station 05",
    gpu: "RTX A6000 48GB",
    cpu: "Threadripper Pro",
    ram: "128GB",
    storage: "2.7TB",
    state: "offline",
    cpuUsage: 0,
    gpuUsage: 0,
    owner: null,
    project: null,
  },
] as const;

export const savedSessions = [
  {
    id: "saved-1",
    name: "교내 자율주행 데이터셋",
    machine: "Lab Station 03",
    specs: "RTX 3090 · 8 Core · 16GB",
    savedAt: "6월 28일 오후 11:42",
    deleteIn: "27일 후",
    size: "84.2GB",
  },
  {
    id: "saved-2",
    name: "과학전람회 예측 모델",
    machine: "Lab Station 01",
    specs: "RTX 4090 · 12 Core · 32GB",
    savedAt: "6월 21일 오후 4:08",
    deleteIn: "20일 후",
    size: "126GB",
  },
];

export const users = [
  { email: "ts250015@ts.hs.kr", sessions: 1, limit: 2, lastSeen: "현재 접속 중", role: "관리자" },
  { email: "ts250021@ts.hs.kr", sessions: 1, limit: 1, lastSeen: "3분 전", role: "학생" },
  { email: "ts250008@ts.hs.kr", sessions: 1, limit: 1, lastSeen: "12분 전", role: "학생" },
  { email: "ts250024@ts.hs.kr", sessions: 0, limit: 2, lastSeen: "어제", role: "관리자" },
  { email: "ts260011@ts.hs.kr", sessions: 0, limit: 1, lastSeen: "6월 24일", role: "학생" },
];

export const activity = [
  { time: "14:32", title: "파일 전송 완료", detail: "dataset-v4.zip · 1.8GB", tone: "green" },
  { time: "13:08", title: "세션을 시작했습니다", detail: "컴퓨터 비전 탐구 · Lab Station 01", tone: "blue" },
  { time: "어제", title: "세션이 보관되었습니다", detail: "교내 자율주행 데이터셋", tone: "violet" },
  { time: "6월 27일", title: "팀원이 추가되었습니다", detail: "ts250042@ts.hs.kr", tone: "blue" },
];
