[/]
object-id-list=['object-0', 'object-1', 'object-2', 'object-3']
toplevel-id-list=['bottom']

[toplevels/bottom]
auto-hide=false
enable-buttons=false
enable-arrows=true
expand=true
orientation='bottom'
screen=0
size=40
background-type='color'
background-color='rgba(0,0,0,0.85)'

[objects/object-0]
object-type='applet'
applet-iid='PanelInternalFactory::MenuBar'
toplevel-id='bottom'
panel-right-stick=false
position=0
locked-down=false

[objects/object-1]
object-type='applet'
applet-iid='WnckletFactory::WindowListApplet'
toplevel-id='bottom'
panel-right-stick=false
position=60
locked-down=false

[objects/object-2]
object-type='applet'
applet-iid='NotificationAreaAppletFactory::NotificationArea'
toplevel-id='bottom'
panel-right-stick=true
position=1
locked-down=false

[objects/object-3]
object-type='applet'
applet-iid='ClockAppletFactory::ClockApplet'
toplevel-id='bottom'
panel-right-stick=true
position=0
locked-down=false
